### ISSUE TITLE
Devices not added?

### ISSUE THREAD

**Issue by shackrock** [pedroandrade1977/Hubitat-Awair-Connect#1]
I followed the instructions but no devices were added to my device list after initializing the app and selecting the Awairs that I wanted to poll in Hubitat.  Do I need to add them manually somehow/somewhere?

**Comment by pedroandrade1977** [comment]
Hi, I would need to see your logs to check. It should be added automatically. Unfortunately my Awair is now unsupported and I cannot test anymore.

**Comment by shackrock** [comment]
I went into "logs" then "past logs" and filtered by the app, and I see this error generated when I click "next" in the setup (I selected 3 different awairs to connect to from the list).

> Awair (Connect) -> createChildDevice(): error creating device Awair - moms: com.hubitat.app.exception.UnknownDeviceTypeException: Device type 'Awair Device' in namespace 'HE_pfta' not found

**Comment by shackrock** [comment]
Ok, I figured it out now, thanks for pointing me to the log page =).

I renamed "Awair Device" to "Awair Device (Cloud)" in order to differentiate it from local polling that I have on one of my awairs (testing both).  Thanks!
